### ISSUE TITLE
No available images on Docker Hub

### ISSUE THREAD

**Issue by Pelid** [bubba-h57/vips_docker_image#1]
The page https://hub.docker.com/r/bubba/vips-docker-image/tags/ is empty by some reason. There is no docker images available for download.

Thanks for Git repo. It is usefull for me.

**Comment by bubba-h57** [comment]
I suspect it is because I hadn't checked anything in for a while. I logged into the Docker Hub and kicked off a manual build. Hopefully that will get the binaries back in there as well. i'm glad this has been useful for you!
